FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    make \
    git

WORKDIR /home/sockets_cpp/

COPY . /home/sockets_cpp/

RUN make linux

# displays the file /dev/null in realtime, aka
# just puts the docker container in idle
CMD ["tail", "-f", "/dev/null"]
